steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    dir: jomstudy-app
    args:
      - build
      - --no-cache
      - --tag
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}
      - --file
      - Dockerfile
      - .

  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}

  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - ${_SERVICE_NAME}
      - --platform=managed
      - --image=${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}
      - --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=${COMMIT_SHA},gcb-build-id=${BUILD_ID},gcb-trigger-id=${_TRIGGER_ID}
      - --region=${_DEPLOY_REGION}
      - --quiet

timeout: 1200s

options:
  logging: CLOUD_LOGGING_ONLY
